project:
  type: website
  output-dir: _output

website:
  title: "Yvesypher's universe"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yvesypher
      - icon: linkedin
        href: https://www.linkedin.com/in/minh-nguyen-1203/
    left:
      - sidebar:notes
      - sidebar:books
      - sidebar:blogs
      
  sidebar:
    - id: notes
      title: "Learning notes"
      style: "docked"
      collapse-level: 3
      contents: learn-notes
    - id: books
      title: "Books"
      style: "docked"
      collapse-level: 3
      contents: books
    - id: blogs
      title: "Random thoughts"
      style: "docked"
      collapse-level: 3
      contents: blogs
        
  search: 
    location: navbar
    type: overlay

format:
  html:
    theme: flatly
    css: styles.css



