---
title: "Phần 1: Làm người"
---

## 1. Định nghĩa con người, làm người:

## 2. Năng lực làm người:

### Năng lực khai phóng (khai minh & giải phóng)

- Khai minh (khai: mở, minh: ánh sáng): mở toang con người tăm tối, con người vô minh, giáo điều, ấu trĩ của mình để đưa ánh sáng của chân lý, sự thật và tự do vào.
    
Triết gia Immanuel Kant: “Khai minh là việc con người đi ra khỏi sự không trưởng thành do chính mình chuốc lấy”
    
- Với cái đầu được khai minh, khai phóng, con người sẽ có khả năng minh định được ai là ai, cái gì là cái gì, mình là ai
    
Minh định (minh: sáng, định: phân):
    
    - khả năng phân biệt một cách sáng suốt được “ai là ai”
    - Khả năng nhìn nhận được sự khác biệt giữa người này với người khác

### Năng lực khai tâm

Khai tâm (khai: mở, tâm: tim): là mở trái tim để rung động trước cái hay cái đẹp (kể cả cái đẹp hữu hình hay vô hình) hay thổn thức trước nỗi đau, phẫn nộ trước cái sai, cái xấu và cái ác; tràn đầy tình thương yêu và giàu lòng trắc ẩn.

## 3. Làm thế nào để có được “năng lực làm người”?